planner_server:
  ros__parameters:
    # Note: expected_planner_frequency = 1/max_planning_time, otherwise a warning will be displayed each time the planner takes more time than 1/expected_planner_frequency seconds to generate a path
    expected_planner_frequency: 0.125
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      debug_visualizations: true
      tolerance: 0.5                    # tolerance for planning if unable to reach exact pose, in meters, for 2D node
      downsample_costmap: false           # whether to downsample the map
      downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      downsample_obstacle_heuristic: false
      use_quadratic_cost_penalty: false   # cost = cost * cost, might require inflation changes on costmap
      allow_unknown: false                # allow traveling in unknown space
      max_iterations: 5000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # maximum number of iterations to attempt to reach goal once in tolerance, 2D only
      max_planning_time: 10.0              # max time in s for planner to plan, smooth, and upsample. Will scale maximum smoothing and upsampling times based on remaining time after planning.
      motion_model_for_search: "REEDS_SHEPP"    # For Hybrid Dubin, Reeds-Shepp
      allow_primitive_interpolation: true  # Interpolate between primitive angles
      angle_quantization_bins: 72         # For Hybrid nodes: Number of angle bins for search
      analytic_expansion_ratio: 2.0       # For Hybrid/Lattice nodes: The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 7.5    # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting (in meters). This should be scaled with minimum turning radius and be no less than 4-5x the minimum radius
      analytic_expansion_max_cost: 200.0  # The maximum single cost for any part of an analytic expansion to contain and be valid, except when necessary on approach to goal
      minimum_turning_radius: 0.5      # For Hybrid/Lattice nodes: minimum turning radius in m of path / vehicle  - Makes robot to take turn in area where it has more space
      reverse_penalty: 1.75                # For Reeds-Shepp model: penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.0                 # For Hybrid nodes: penalty to apply if motion is changing directions, must be >= 0
      non_straight_penalty: 1.3         # For Hybrid nodes: penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 5.75                  # For Hybrid nodes: penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.115       # For Hybrid/Lattice nodes: penalty to prefer later maneuvers before earlier along the path. Saves search time since earlier nodes are not expanded until it is necessary. Must be >= 0.0 and <= 1.0
      lookup_table_size: 5.0               # For Hybrid nodes: Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: True      # For Hybrid nodes: Cache the obstacle map dynamic programming distance expansion heuristic between subsequent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      goal_heading_mode: "DEFAULT"        # Options: DEFAULT, BIDIRECTIONAL, ALL_DIRECTION
      coarse_search_resolution: 1         # Used with ALL_DIRECTION. Reduces search time of analytic expansions.
      terminal_checking_interval: 5000    # Number of iterations between checking if the goal has been cancelled or planner timed out
      smooth_path: false                   # For Lattice/Hybrid nodes: Whether or not to smooth the path, always true for 2D nodes.
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2
        refinement_num: 2